import { App } from "@octokit/app";

let app: App | null = null;

function getApp(): App {
  if (!app) {
    const privateKey = Buffer.from(
      process.env.GITHUB_APP_PRIVATE_KEY!,
      "base64"
    ).toString("utf-8");
    app = new App({
      appId: process.env.GITHUB_APP_ID!,
      privateKey,
      webhooks: { secret: process.env.GITHUB_APP_WEBHOOK_SECRET! },
    });
  }
  return app;
}

export interface CreatePRParams {
  installationId: number;
  owner: string;
  repo: string;
  tenantId: string;
  tenantName: string;
  yamlContent: string;
}

export async function createTenantPR(params: CreatePRParams): Promise<string> {
  const { installationId, owner, repo, tenantId, tenantName, yamlContent } =
    params;
  const octokit = await getApp().getInstallationOctokit(installationId);

  // Get default branch SHA
  const { data: repoData } = await octokit.rest.repos.get({ owner, repo });
  const defaultBranch = repoData.default_branch;
  const { data: ref } = await octokit.rest.git.getRef({
    owner,
    repo,
    ref: `heads/${defaultBranch}`,
  });
  const sha = ref.object.sha;

  // Create branch
  const branchName = `feat/onboard-${tenantId}`;
  await octokit.rest.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branchName}`,
    sha,
  });

  // Create file
  const filePath = `gitops/tenants/tenant-${tenantId}.yaml`;
  await octokit.rest.repos.createOrUpdateFileContents({
    owner,
    repo,
    path: filePath,
    message: `feat: onboard ${tenantName} tenant`,
    content: Buffer.from(yamlContent).toString("base64"),
    branch: branchName,
  });

  // Create PR
  const { data: pr } = await octokit.rest.pulls.create({
    owner,
    repo,
    title: `feat: onboard ${tenantName}`,
    body: `## Onboard ${tenantName}\n\nThis PR was automatically generated by the LogClaw onboarding wizard.\n\nOnce merged, ArgoCD will detect this file and deploy the full LogClaw stack for \`${tenantId}\` within ~30 minutes.\n\n### What's included\n- Tenant namespace + NetworkPolicy baseline\n- Kafka 3-broker KRaft cluster\n- OpenSearch 3-node cluster\n- Flink anomaly detection pipeline\n- Ticketing agent with configured integrations\n\n### Next steps\n1. Review the generated values\n2. Merge this PR\n3. Monitor deployment in the LogClaw dashboard`,
    head: branchName,
    base: defaultBranch,
  });

  return pr.html_url;
}
