import { Octokit } from "@octokit/rest";

/**
 * Edge-compatible base64 encoder.
 * btoa() throws on chars above U+00FF, so we go through TextEncoder first.
 */
function encodeBase64(str: string): string {
  const bytes = new TextEncoder().encode(str);
  let bin = "";
  const chunk = 8192;
  for (let i = 0; i < bytes.length; i += chunk) {
    bin += String.fromCharCode(...bytes.subarray(i, i + chunk));
  }
  return btoa(bin);
}

/**
 * No module-level singleton — Edge Workers are stateless per request.
 * Each invocation gets a fresh Octokit instance.
 */
function getOctokit(): Octokit {
  // GITHUB_APP_PRIVATE_KEY is expected to be a base64-encoded PEM string.
  const privateKey = atob(process.env.GITHUB_APP_PRIVATE_KEY!);

  return new Octokit({
    authStrategy: null, // We'll use installation-specific auth or app auth
    auth: {
      appId: process.env.GITHUB_APP_ID!,
      privateKey,
    },
  });
}

export interface CreatePRParams {
  installationId: number;
  owner: string;
  repo: string;
  tenantId: string;
  tenantName: string;
  yamlContent: string;
}

export async function createTenantPR(params: CreatePRParams): Promise<string> {
  const { installationId, owner, repo, tenantId, tenantName, yamlContent } =
    params;
  const appOctokit = getOctokit();

  // Suppress unused variable warning — installationId logged for observability
  console.log(`Creating PR for tenant=${tenantId} installationId=${installationId}`);

  // Get default branch SHA
  const { data: repoData } = await appOctokit.rest.repos.get({ owner, repo });
  const defaultBranch = repoData.default_branch;
  const { data: ref } = await appOctokit.rest.git.getRef({
    owner,
    repo,
    ref: `heads/${defaultBranch}`,
  });
  const sha = ref.object.sha;

  // Create branch
  const branchName = `feat/onboard-${tenantId}`;
  await appOctokit.rest.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branchName}`,
    sha,
  });

  // Create file — use edge-compatible base64 encoder
  const filePath = `gitops/tenants/tenant-${tenantId}.yaml`;
  await appOctokit.rest.repos.createOrUpdateFileContents({
    owner,
    repo,
    path: filePath,
    message: `feat: onboard ${tenantName} tenant`,
    content: encodeBase64(yamlContent),
    branch: branchName,
  });

  // Create PR
  const { data: pr } = await appOctokit.rest.pulls.create({
    owner,
    repo,
    title: `feat: onboard ${tenantName}`,
    body: `## Onboard ${tenantName}\n\nThis PR was automatically generated by the LogClaw onboarding wizard.\n\nOnce merged, ArgoCD will detect this file and deploy the full LogClaw stack for \`${tenantId}\` in namespace \`logclaw-${tenantId}\` within ~25 minutes.\n\n### What's included\n- Tenant namespace + RBAC + NetworkPolicy baseline\n- Kafka KRaft cluster (Strimzi 0.50.1)\n- OpenSearch 3-node cluster (Opster operator)\n- Vector.dev ingestion pipeline\n- Flink anomaly scoring (if enabled)\n- ML Engine with Feast feature store (if enabled)\n- Ticketing agent with configured integrations\n\n### Deployment timeline\n| Time | Milestone |\n|---|---|\n| T+2 min | Namespace, RBAC, secrets |\n| T+5 min | Kafka ready |\n| T+8 min | OpenSearch green |\n| T+12 min | Vector ingestion connected |\n| T+20 min | Ticketing agent consuming |\n| T+25 min | Full stack operational |\n\n### Next steps\n1. Review the generated values in this PR\n2. Merge to trigger ArgoCD sync\n3. Monitor: \`kubectl get pods -n logclaw-${tenantId}\`\n4. View the live dashboard at [app.logclaw.ai](https://app.logclaw.ai)`,
    head: branchName,
    base: defaultBranch,
  });

  return pr.html_url;
}
